### ISSUE TITLE
这个用不了呀

### ISSUE THREAD

**Issue by shixinxin1111** [rare-treasure/vue-count-to#1]
这个用不了呀
![image](https://user-images.githubusercontent.com/37872645/102841571-24260800-4440-11eb-9bf1-22db75025dd1.png)

![image](https://user-images.githubusercontent.com/37872645/102841584-2daf7000-4440-11eb-8b5f-81679ea997c5.png)

**Comment by xiaofan9** [comment]
目前暂时只支持 全局引入的方式使用，明后两天会更新一个支持局部引入的版本

**Comment by xiaofan9** [comment]
> 这个用不了呀
> ![image](https://user-images.githubusercontent.com/37872645/102841571-24260800-4440-11eb-9bf1-22db75025dd1.png)
> 
> ![image](https://user-images.githubusercontent.com/37872645/102841584-2daf7000-4440-11eb-8b5f-81679ea997c5.png)

最新版本，请使用这个方式使用：

```javascript
<template>
  <count-to></count-to>
</template>

<script>
import { CountTo } from 'vue3-count-to';

export default {
  components: {
    CountTo
  }
}
</script>
```
